from libevent.event import Event
from typing import Dict


class Span(object):
    """Represents an active span. Create via Tracer.start_span."""
    def __init__(self, trace_id: str, parent_id: str, id: str, ev: Event): ...
    def add_context(self, data: Dict) -> None: ...
    def add_context_field(self, key: str, value: str) -> None: ...
    def fields(self) -> Dict: ...
    def remove_context_field(self, key) -> None: ...
